#!/bin/bash
# Check terminal settings against reference
#
# Before using this script, set TTYPATH for your system
#
if [ -z "$TTYPATH" ]; then
	echo "Please set TTYPATH for your system in this script"
	echo "or set TTYPATH in the environment before running this script."
	exit 1
fi
# For example, on Linux systems, you might set:
# TTYPATH=/dev/pts
#
# then create a reference by running:
#
#    chktty terminal-number -r
#
# for example:
#
#   TTYPATH=/dev/pts
#   chktty 0 -r
#
# where /dev/pts/0 is the terminal you want to use as reference.
# Then use this script to compare the settings of other terminals
#
# Usage: chktty terminal-number [-r to create reference]
#
if [ $# -lt 1 ]; then
	echo usage: "$0" terminal-number [-r to create reference]
	exit 1
fi
if [ ! -e "$TTYPATH"/"$1" ]; then
	echo "$TTYPATH/$1 does not exist"
	exit 1
fi
if [ "$2" == "-r" ]; then
	echo "Creating reference stty settings in" "$CMENU_HOME/test/stty.ref"
	mkdir -p "$CMENU_HOME"/test
	stty -a <"$TTYPATH"/"$1" | sed 's/ = /=/g' | tr ' ' '\n' >"$CMENU_HOME"/test/stty.ref
	exit 0
fi
stty -a <"$TTYPATH"/"$1" | sed 's/ = /=/g' | tr ' ' '\n' >"$CMENU_HOME"/test/stty"$1".a
diff -W40 -y --suppress-common-lines "$CMENU_HOME"/test/stty"$1".a "$CMENU_HOME"/test/stty.ref
