#!/bin/bash
#
# Use gdb to run the 'pick' program with specific arguments
# and redirect output to a file
if [ ! -s "gdbcmds" ]; then
	echo "set pagination off" >gdbcmds
	echo "run" >>gdbcmds
	echo "quit" >>gdbcmds
fi
gdb -x gdbcmds -q --args pick -S "lf ./ .*\.c$" -c vi
