#ifndef UI_NCURSES_INTERNAL_H
#define UI_NCURSES_INTERNAL_H 1

#ifdef __cplusplus
extern "C" {
#endif

/** @file ui_ncurses_internal.h
   @ingroup ui_ncurses
   @brief Internal header for the NCurses UI backend.

   This header defines the concrete (non-opaque) layouts of UiRuntime and
   UiSurface for the NCurses backend.  It must only be included by NCurses
   backend source files — never by application code.
*/

#define _XOPEN_SOURCE_EXTENDED 1
#define _GNU_SOURCE
#define NCURSES_WIDECHAR 1
#include <ncursesw/ncurses.h>
#include <ncursesw/panel.h>
#include <stdbool.h>
#include <stdint.h>

#define UIKEY_RESIZE KEY_RESIZE
#define UIKEY_UP KEY_UP
#define UIKEY_RIGHT KEY_RIGHT
#define UIKEY_DOWN KEY_DOWN
#define UIKEY_LEFT KEY_LEFT
#define UIKEY_IC KEY_IC
#define UIKEY_DC KEY_DC
#define UIKEY_BACKSPACE KEY_BACKSPACE
#define UIKEY_NPAGE KEY_NPAGE
#define UIKEY_PPAGE KEY_PPAGE
#define UIKEY_HOME KEY_HOME
#define UIKEY_END KEY_END
#define UIKEY_F01 KEY_F(1)
#define UIKEY_F02 KEY_F(2)
#define UIKEY_F03 KEY_F(3)
#define UIKEY_F04 KEY_F(4)
#define UIKEY_F05 KEY_F(5)
#define UIKEY_F06 KEY_F(6)
#define UIKEY_F07 KEY_F(7)
#define UIKEY_F08 KEY_F(8)
#define UIKEY_F09 KEY_F(9)
#define UIKEY_F10 KEY_F(10)
#define UIKEY_F11 KEY_F(11)
#define UIKEY_F12 KEY_F(12)
#define UIKEY_ENTER KEY_ENTER
#define UIKEY_CLEAR KEY_CLEAR
#define UIKEY_BEG KEY_BEG
#define UIKEY_CANCEL KEY_CANCEL
#define UIKEY_CLOSE KEY_CLOSE
#define UIKEY_COMMAND KEY_COMMAND
#define UIKEY_COPY KEY_COPY
#define UIKEY_EXIT KEY_EXIT
#define UIKEY_PRINT KEY_PRINT
#define UIKEY_REFRESH KEY_REFRESH
#define UIKEY_MOUSE KEY_MOUSE
#define UIKEY_RSHIFT KEY_SRIGHT
#define UIKEY_LSHIFT KEY_SLEFT

#ifdef TO_BE_ADDED
#define UIKEY_INVALID KEY_INVALID
#define UIKEY_CAPS_LOCK KEY_CAPS_LOCK
#define UIKEY_SCROLL_LOCK KEY_SCROLL_LOCK
#define UIKEY_NUM_LOCK KEY_NUM_LOCK
#define UIKEY_PRINT_SCREEN KEY_PRINT_SCREEN
#define UIKEY_BUTTON1 KEY_BUTTON1
#define UIKEY_BUTTON2 KEY_BUTTON2
#define UIKEY_BUTTON3 KEY_BUTTON3
#define UIKEY_MEDIA_PLAY KEY_MEDIA_PLAY
#define UIKEY_MEDIA_PAUSE KEY_MEDIA_PAUSE
#define UIKEY_MEDIA_PPAUSE KEY_MEDIA_PPAUSE
#define UIKEY_MEDIA_REV KEY_MEDIA_REV
#define UIKEY_MEDIA_STOP KEY_MEDIA_STOP
#define UIKEY_MEDIA_FF KEY_MEDIA_FF
#define UIKEY_MEDIA_REWIND KEY_MEDIA_REWIND
#define UIKEY_MEDIA_NEXT KEY_MEDIA_NEXT
#define UIKEY_MEDIA_PREV KEY_MEDIA_PREV
#define UIKEY_MEDIA_RECORD KEY_MEDIA_RECORD
#define UIKEY_MEDIA_LVOL KEY_MEDIA_LVOL
#define UIKEY_MEDIA_RVOL KEY_MEDIA_RVOL
#define UIKEY_MEDIA_MUTE KEY_MEDIA_MUTE
#define UIKEY_SIGNAL KEY_SIGNAL
#define UIKEY_EOF KEY_EOF
#endif
#define UIKEY_BTAB KEY_BTAB
#define UIKEY_RETURN KEY_ENTER
#define UIKEY_TAB 0x09
#define UIKEY_ESCAPE 0x1B
#define UIKEY_SPACE 0x20
#define UIKEY_MOD_SHIFT 1
#define UIKEY_MOD_ALT 2
#define UIKEY_MOD_CTRL 4
#define UIKEY_MOD_SUPER 8
#define UIKEY_MOD_HYPER 16
#define UIKEY_MOD_META 32
#define UIKEY_MOD_CAPSLOCK 64
#define UIKEY_MOD_NUMLOCK 128
#define UIKEY_NONE 0700
#define UIKEY_CHAR 0703

#define UIKEY_SCROLL_UP BUTTON4_PRESSED
#define UIKEY_SCROLL_DOWN BUTTON5_PRESSED
#define UIKEY_BUTTON1_CLICKED BUTTON1_CLICKED
#define UIKEY_BUTTON1_PRESSED BUTTON1_PRESSED
#define UIKEY_BUTTON1_RELEASED BUTTON1_RELEASED
#define UIKEY_BUTTON2_CLICKED BUTTON2_CLICKED
#define UIKEY_BUTTON2_PRESSED BUTTON2_PRESSED
#define UIKEY_BUTTON2_RELEASED BUTTON2_RELEASED
#define UIKEY_BUTTON3_CLICKED BUTTON3_CLICKED
#define UIKEY_BUTTON3_PRESSED BUTTON3_PRESSED
#define UIKEY_BUTTON3_RELEASED BUTTON3_RELEASED
#define UIKEY_BUTTON4_CLICKED BUTTON4_CLICKED
#define UIKEY_BUTTON4_PRESSED BUTTON4_PRESSED
#define UIKEY_BUTTON4_RELEASED BUTTON4_RELEASED
#define UIKEY_BUTTON5_CLICKED BUTTON5_CLICKED
#define UIKEY_BUTTON5_PRESSED BUTTON5_PRESSED
#define UIKEY_BUTTON5_RELEASED BUTTON5_RELEASED
#define UIKEY_BUTTON1 0730
#define UIKEY_BUTTON2 0731
#define UIKEY_BUTTON3 0732
#define UIKEY_BUTTON4 0733
#define UIKEY_BUTTON5 0734
#define UIKEY_SIGNAL 0737

#define UI_MASK WA_ATTRIBUTES
#define UI_NORMAL WA_NORMAL
#define UI_STANDOUT WA_STANDOUT
#define UI_UNDERLINE WA_UNDERLINE
#define UI_REVERSE WA_REVERSE
#define UI_BLINK WA_BLINK
#define UI_DIM WA_DIM
#define UI_BOLD WA_BOLD
#define UI_ALTCHARSET WA_ALTCHARSET
#define UI_INVIS WA_INVIS
#define UI_PROTECT WA_PROTECT
#define UI_UNDERCURL WA_DIM
#define UI_STRUCK WA_INVIS
#define UI_NONE WA_NORMAL
#define UI_ITALIC WA_ITALIC

#ifdef __cplusplus
}
#endif
#endif
