local Stdbg = "#000020"
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = "#ffdf00" })
vim.api.nvim_set_hl(0, "Type", { fg = "#0f8fff" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#00f09f" })
vim.api.nvim_set_hl(0, "Character", { fg = "#d0d0d0" })
vim.api.nvim_set_hl(0, "constructor", { fg = "#90ffbf" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#00ffbf" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#70e0ff" })
vim.api.nvim_set_hl(0, "Define", { fg = "#00dfff" })
vim.api.nvim_set_hl(0, "Include", { fg = "#3fcfbf" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#50d0ff" })
vim.api.nvim_set_hl(0, "Number", { fg = "#c0ffe0" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#ff0fff" })
vim.api.nvim_set_hl(0, "@lsp.type.variable", { fg = "#ffc700" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#00dfaf" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#00dfaf" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#00d090" })
vim.api.nvim_set_hl(0, "@property", { fg = "#ffc700" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#ffc700" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#00c700" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#d700d0" })
vim.api.nvim_set_hl(0, "Function", { fg = "#ff5000" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#b00000" })
vim.api.nvim_set_hl(0, "String", { fg = "#f0f090" })
vim.api.nvim_set_hl(0, "WhichKeyBorder", { bg = Stdbg, fg = "#ff2f00" })
vim.api.nvim_set_hl(0, "WhichKeyNormal", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "WhichKeyTitle", { bg = Stdbg, fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { bg = Stdbg, fg = "#00f000" })
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { bg = Stdbg, fg = "#f000f0" })
vim.api.nvim_set_hl(0, "SnacksNormal", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksNormalNC", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksWinbar", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksWinbarNC", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksDashboardNormal", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksInputNormal", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksInputBorder", { bg = Stdbg, fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "SnacksInputTitle", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "SnacksNotifierHistoryTitle", { bg = Stdbg, fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "LineNRAbove", { fg = "#4f6fff", bg = "NONE" })
vim.api.nvim_set_hl(0, "LineNRBelow", { fg = "#4f6fff", bg = "NONE" })
vim.api.nvim_set_hl(0, "LineNR", { fg = "#4f6fff", bg = "NONE" })
vim.api.nvim_set_hl(0, "DapUIBreakpointsLine", { fg = "#ff0000", bg = "NONE" })
vim.api.nvim_set_hl(0, "DapUILineNumber", { fg = "#00afaf", bg = "NONE" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#ffd700", bg = "NONE" })
vim.api.nvim_set_hl(0, "SnacksScratchTitle", { bg = Stdbg, fg = "#00f0c0" })
vim.api.nvim_set_hl(0, "SnacksDashboardHeader", { bg = Stdbg, fg = "#ff2f00" })
vim.api.nvim_set_hl(0, "HistoryTitle", { bg = Stdbg, fg = "#ffffff" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#e0d0d0" })
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", { fg = "#e0ffd0" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#f02f00" })
