#!/bin/bash
# @name nmi_watchdog
# @desc Enable or disable nmi_watchdog kernel parameter. This is used to detect
# and debug system hangs. When enabled, the kernel will trigger a non-maskable
# interrupt (NMI) if the system becomes unresponsive for a certain period of
# time. This can help identify the cause of the hang and provide useful
# information for troubleshooting.
# @usage nmi_watchdog [enable|disable]
#
if [ "$(id -un)" != "root" ]; then
    echo Please run as root
    exit 1
fi
if [ "$1" = "disable" ]; then
    echo 0 >/proc/sys/kernel/nmi_watchdog
    echo nmi_watchdog disabled
else
    if [ "$1" = "enable" ]; then
        echo 1 >/proc/sys/kernel/nmi_watchdog
        echo nmi_watchdog enabled
    else
        echo usage: "$0" "[enable][disable]"
    fi
fi
