#!/bin/bash
grep NCURSES compile_commands.json >/dev/null 2>&1
if [ "$?" = "0" ]; then
    if [ "$1" = "s" ]; then
        cp compile_commands_notcurses.json compile_commands.json
        echo NCURSES to NOTCURSES
    else
        echo NCURSES
    fi
else
    grep NOTCURSES compile_commands.json >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        if [ "$1" = "s" ]; then
            cp compile_commands_ncurses.json compile_commands.json
            echo NOTCURSES to NCURSES
        else
            echo NOTCURSES
        fi
    fi
fi
