#!/bin/bash
# @brief chkui - check UI library linkage and selection

if [ "$1" = "-h" -o "$1" = "-?" -o "$1" = "--help" ]; then
    echo chkui [-s][-h]
    echo without arguments, chk reports:
    echo menu - UI library linkage \(ncurses or notcurses\)
    echo Makefile - UI library selection \(NOTCURSES_UI or NCUAL_UI\) echo compile_commands.json - UI library selection \(NCURSES or NOTCURSES\)
    echo Note: compile_commands.json is used by clangd for code completion and navigation.
    echo -s switches compile_commands.json between NCURSES and NOTCURSES
    echo -h, -?, --help prints this help message
    exit 0
fi
NOTCURSES=0
NCURSES=0
grep NCURSES compile_commands.json >/dev/null 2>&1
if [ ! -f ./menu ]; then
    echo menu not found - linkage check not possible
else
    objdump -p ./menu | grep -E "NEEDED.*(notcurses)" >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        echo menu linked with notcurses
    else
        objdump -p ./menu | grep -E "NEEDED.*(ncurses)" >/dev/null 2>&1
        if [ "$?" = "0" ]; then
            echo menu linked with ncurses
        fi
    fi
fi
# CMake
grep NOTCURSES UI.cmk >/dev/null 2>&1
if [ "$?" = "0" ]; then
    echo CMake - NOTCURSES
    if [ "$1" = "-s" ]; then
        CMK_SWITCH=1
    fi
else
    grep UAL_UI UI.mk Makefile >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        echo CMake - NCURSES
        if [ "$1" = "-s" ]; then
            CMK_SWITCH=2
        fi
    fi
fi
# Makefile
grep NOTCURSES UI.mk >/dev/null 2>&1
if [ "$?" = "0" ]; then
    echo Makefile - NOTCURSES
    if [ "$1" = "-s" ]; then
        MK_SWITCH=1
    fi
else
    grep UAL_UI UI.mk Makefile >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        echo Makefile - NCURSES
        MK_SWITCH=2
    fi
fi
grep NOTCURSES compile_commands.json >/dev/null 2>&1
if [ "$?" = "0" ]; then
    echo compile_commands.json - NOTCURSES
    if [ "$1" = "-s" ]; then
        CCJ_SWITCH=1
    fi
else
    grep UAL_UI compile_commands.json >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        echo compile_commands.json - NCURSES
        CCJ_SWITCH=2
    fi
fi
if [ "$1" = "-s" ]; then
    if [ "$CMK_SWITCH" -ne "$MK_SWITCH" -o $CMK_SWITCH -ne $CCJ_SWITCH ]; then
        echo "Warning: CMake, Makefile, compile_commands.json UI build switch mismatch"
        echo "Resolve manually by editing UI.mk, UI.cmk, compile_commands.json"
        exit 1
    fi
    if [ "$CMK_SWITCH" = "1" ]; then
        echo CMake switching to NCURSES
        echo "cmake .. -D UI=UAL_UI" >UI.cmk
        echo Makefile switching to NCURSES
        echo "UI?=\"-DUAL_UI\"" >UI.mk
        echo compile_commands.json switching to NCURSES
        cp compile_commands_ncurses.json compile_commands.json
    else
        if [ "$CMK_SWITCH" = "2" ]; then
            echo CMake switching to NOTCURSES
            echo "cmake .. -D UI=NOTCURSES_UI" >UI.cmk
            echo Makefile switching to NOTCURSES
            echo "UI?=\"-DNOTCURSES_UI\"" >UI.mk
            echo compile_commands.json switching to NOTCURSES
            cp compile_commands_notcurses.json compile_commands.json
        fi
    fi
fi
