#!/bin/bash

# This script is used to build the project using CMake with different UI options.

# Using CMake

cd build

# To build C-Menu with the NCurses library:

cmake .. -D UI=UAL_UI

# To build C-Menu with the Notcurses library

# cmake .. -D UI=NOTCURSES_UI

# Using GNU Makefile
#
# Edit the Makefile and uncomment:

# to build with the NCurses library

# UI=UAL_UI

# to build with the Notcurses library

# UI=NOTCURSES_UI

# Then run:

make

make install

# If you use the clangd language server, you will want to build with cmake and
# put the compile_commands.json in the root of the project.

# compile_commands.json is generated by default in the build directory, so you
# can copy it to the root of the project with:

cp compile_commands.json ..
