/bin/ls -Fl --time-style=+"%y%m%d %H%M" --color=always \
    /etc/ld.so.conf.d/CMenu.conf \
    /etc/pam.d/rsh-auth \
    /etc/pam.d/rsh-auth-pc \
    /home/bill/menuapp/bin/amort \
    /home/bill/menuapp/bin/ckeys \
    /home/bill/menuapp/bin/enterchr \
    /home/bill/menuapp/bin/enterstr \
    /home/bill/menuapp/bin/form \
    /home/bill/menuapp/bin/iloan \
    /home/bill/menuapp/bin/menu \
    /home/bill/menuapp/bin/pick \
    /home/bill/menuapp/bin/rsh \
    /home/bill/menuapp/bin/stripansi \
    /home/bill/menuapp/bin/view \
    /home/bill/menuapp/bin/whence \
    /home/bill/menuapp/include/cm.h \
    /home/bill/menuapp/include/common.h \
    /home/bill/menuapp/include/form.h \
    /home/bill/menuapp/include/menu.h \
    /home/bill/menuapp/include/pick.h \
    /home/bill/menuapp/include/view.h \
    /home/bill/menuapp/lib64/libcm.a \
    /home/bill/menuapp/lib64/libcm.so \
    /home/bill/menuapp/lib64/libcm.so.0 \
    /home/bill/menuapp/lib64/libcm.so.0.2.9 \
    /home/bill/menuapp/man/man1/cmenu.1.gz \
    /home/bill/menuapp/man/man1/lf.1.gz \
    /home/bill/menuapp/man/man1/rsh.1.gz >manifest.txt
