#!/bin/bash

if ! which scan-build >/dev/null 2>&1; then
	echo "scan-build is required to run this script"
	exit 1
fi
if [ "$#" = 1 ]; then
	if [ "$1" = "-h" ]; then
		echo "sb -r : remove all scan-build temp directories"
		echo "sb -c : check for scan-build temp directories"
		echo "sb    : run scan-build for cmenu"
		echo "sb -h : help (this message)"
		exit 0
	fi
	if [ "$1" = "-r" ]; then
		find /tmp -maxdepth 1 -depth -name 'scan-build*' -type d -exec rm -rf {} \;
		exit 0
	fi
	if [ "$1" = "-c" ]; then
		find /tmp -maxdepth 1 -depth -name 'scan-build*' -type d
		exit 0
	fi
fi
echo "Running scan-build for cmenu..."
scan-build \
	--use-analyzer=/usr/bin/clang \
	-plist-html \
	--html-title="cmenu Scan-Build" \
	-enable-checker unix.cstring.NulArg \
	-enable-checker unix.API \
	-enable-checker unix.Malloc \
	-enable-checker core.NullDereference \
	make clean all -o /home/bill/scan-build >scan-build.log 2>&1
# -enable-checker debug.ViewCallGraph
# -enable-checker debug.DumpCallGraph \
# -enable-checker debug.ViewCFG
# -enable-checker debug.DumpCFG \
# --status-bugs \
