#ifndef VERSION_H
#define VERSION_H

#define CM_VERSION_MAJOR @PROJECT_VERSION_MAJOR @
#define CM_VERSION_MINOR @PROJECT_VERSION_MINOR @
#define CM_VERSION_PATCH @PROJECT_VERSION_PATCH @
#define CM_VERSION "0.2.9"

#endif
